### get chat list
GET http://localhost:6688/api/chat
Authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDA5MDIxOTAsImV4cCI6MTc0MTUwNjk5MCwibmJmIjoxNzQwOTAyMTkwLCJpc3MiOiJjaGF0X3NlcnZlciIsImF1ZCI6ImNoYXRfd2ViIiwiaWQiOjEsImZ1bGxuYW1lIjoidmluY2VudCIsImVtYWlsIjoidmluY2VudEB0ZXN0LmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAzLTAyVDAxOjU5OjEyLjg3NzY4N1oifQ.LcIAEeA_TqPeTeY6iMjt3_Da81YQ92VcA0WMtCWaKX8jaQBRyqrmlLaolU3qd0yWH7ae8tGD1aBz6bGtzMN1Cw

### get chat list with token on url
GET http://localhost:6688/api/chat?token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDA5MDIxOTAsImV4cCI6MTc0MTUwNjk5MCwibmJmIjoxNzQwOTAyMTkwLCJpc3MiOiJjaGF0X3NlcnZlciIsImF1ZCI6ImNoYXRfd2ViIiwiaWQiOjEsImZ1bGxuYW1lIjoidmluY2VudCIsImVtYWlsIjoidmluY2VudEB0ZXN0LmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI1LTAzLTAyVDAxOjU5OjEyLjg3NzY4N1oifQ.LcIAEeA_TqPeTeY6iMjt3_Da81YQ92VcA0WMtCWaKX8jaQBRyqrmlLaolU3qd0yWH7ae8tGD1aBz6bGtzMN1Cw